---
# This is necessary in order to unarchive the Terraform zip and the
# terraform-docs tarball.
- name: Install tar and unzip
  ansible.builtin.package:
    name:
      - tar
      - unzip

- name: Download and install Terraform binary
  ansible.builtin.unarchive:
    creates: "{{ terraform_install_dir }}/terraform"
    dest: "{{ terraform_install_dir }}"
    group: "{{ terraform_group }}"
    mode: "{{ terraform_mode }}"
    owner: "{{ terraform_owner }}"
    remote_src: yes
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip

- name: Download and install terraform-docs binary
  ansible.builtin.unarchive:
    creates: "{{ terraform_install_dir }}/terraform-docs"
    dest: "{{ terraform_install_dir }}"
    group: "{{ terraform_group }}"
    # The archive also includes a README and a LICENSE file, but we
    # don't want those.
    include: terraform-docs
    mode: "{{ terraform_mode }}"
    owner: "{{ terraform_owner }}"
    remote_src: yes
    src: https://github.com/terraform-docs/terraform-docs/releases/download/v{{ terraform_docs_version }}/terraform-docs-v{{ terraform_docs_version }}-linux-amd64.tar.gz
