---
- name: Load var file based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars"

# This is necessary in order to unarchive the Terraform zip and the
# terraform-docs tarball.
- name: Install tar and unzip
  ansible.builtin.package:
    name:
      - tar
      - unzip

- name: Download and install Terraform binary
  ansible.builtin.unarchive:
    creates: "{{ terraform_install_dir }}/terraform"
    dest: "{{ terraform_install_dir }}"
    group: "{{ terraform_group }}"
    mode: "{{ terraform_mode }}"
    owner: "{{ terraform_owner }}"
    remote_src: true
    src: "{{ terraform_url }}"

- name: Download and install terraform-docs binary
  ansible.builtin.unarchive:
    creates: "{{ terraform_install_dir }}/terraform-docs"
    dest: "{{ terraform_install_dir }}"
    group: "{{ terraform_group }}"
    # The archive also includes a README and a LICENSE file, but we
    # don't want those.
    include: terraform-docs
    mode: "{{ terraform_mode }}"
    owner: "{{ terraform_owner }}"
    remote_src: true
    src: "{{ terraform_docs_url }}"
