---
# This is necessary in order to unarchive the Terraform zip and the
# terraform-docs tarball.
- name: Install unzip
  ansible.builtin.package:
    name:
      - tar
      - unzip

- name: Download and install terraform binary
  ansible.builtin.unarchive:
    creates: "{{ install_dir }}/terraform"
    dest: "{{ install_dir }}"
    group: "{{ group }}"
    mode: "{{ mode }}"
    owner: "{{ owner }}"
    remote_src: yes
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip

- name: Download and install terraform-docs binary
  ansible.builtin.unarchive:
    creates: "{{ install_dir }}/terraform-docs"
    dest: "{{ install_dir }}"
    group: "{{ group }}"
    # The archive also includes a README and a LICENSE file, but we
    # don't want those.
    include: terraform-docs
    mode: "{{ mode }}"
    owner: "{{ owner }}"
    remote_src: yes
    # ansible-lint generates a warning that "lines should be no longer
    # than 160 characters" here", but there is no good way to break up
    # this URL
    src: https://github.com/terraform-docs/terraform-docs/releases/download/v{{ terraform_docs_version }}/terraform-docs-v{{ terraform_docs_version }}-linux-amd64.tar.gz  # noqa 204
